### ISSUE TITLE
Parser produces a error if first line in the config it's empty line.

### ISSUE THREAD

**Issue by jitlogan** [jitlogan/xbkconfig#3]
/home/test/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/parslet-1.7.1/lib/parslet/cause.rb:70:in `raise': Extra input after last repetition at line 1 char 1. (Parslet::ParseFailed)
	from /home/test/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/parslet-1.7.1/lib/parslet/atoms/base.rb:49:in `parse'
	from /home/test/Projects/xbkconfig/xbkconfig.rb:12:in `parse'
	from agar_bindings.rb:7:in `<main>'
:~$

**Comment by jitlogan** [comment]
Fixed.
